events {}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/m;

    upstream backend_apis {
        server api1:5000;
        server api2:5000;
        server api3:5000;
    }

    # HTTP -> HTTPS redirect
    server {
        listen 80;
        server_name localhost;

        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            proxy_pass http://backend_apis;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /task {
            limit_req zone=api_limit burst=2 nodelay;

            proxy_pass http://backend_apis/task;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}